### PR TITLE
Remove 140+ duplicated domains

### PR DESCRIPTION
**Pull request by liruqi**
HK and TW top-level domains are in the list, so HK & TW domains can be removed to reduce pac file size.

### CODE REVIEW

**Comment by clowwindy** [comment]
Looks good to me. There're a few small PEP8 violations: https://travis-ci.org/clowwindy/gfwlist2pac/jobs/48983159#L129

And you can use [`for...else`](https://docs.python.org/2/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops) instead of the `duplicated` variable.

Thanks for the great job!

**Comment by liruqi** [comment]
Nice. First time using `for...else` syntax.

**Comment by clowwindy** [comment]
I think you can indent this way:

```
    proxy_content = proxy_content.replace('__DOMAINS__',
                                          json.dumps(domains_dict,
                                                     indent=2,
                                                     sort_keys=True))
```

**Comment by liruqi** [comment]
@clowwindy PEP8 violations are fixed.

**Comment by clowwindy** [comment]
Thanks, merged.

**Pull request merged**
